# Generated by Django 5.0.6 on 2024-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название рассылки')),
                ('sent_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('sent_time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('periodicity', models.CharField(max_length=50, verbose_name='Периодичность')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
