# Generated by Django 5.0.6 on 2024-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmails', '0004_alter_mailing_options_remove_message_mailing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='client',
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Неуспешно', 'Неуспешно')], max_length=50, verbose_name='Cтатус рассылки'),
        ),
    ]
